server:
  port: 8888

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        - id: service-provider
          uri: http://127.0.0.1:8070
          predicates:
          - Path=/provider/**
          filters:
            - RewritePath=/provider(?<segment>/?.*), $\{segment}
        - id: service-consumer
          uri: http://127.0.0.1:8080
          predicates:
          - Path=/consumer/**
          filters:
            - RewritePath=/consumer(?<segment>/?.*), $\{segment}
